version: "3.7"
services:
  khistory:
    build: .
    environment:
      - KENTIK_API_USER='johndoe@expans.com'
      - KENTIK_API_PASSWORD='adsf8960svypzsyadf06g'
    volumes:
      - "/tmp:/usr/src/app/output"
      - "/tmp/input:/usr/src/app/input"
    command: [ './sl.py' ]
  harperdb:
    image: harperdb/hdb
    expose:
      - "9925"
    container_name: harperdb
    volumes:
      - harper_db:/opt/HarperDB/hdb
    networks:
      - dev
    restart: always